<?xml version="1.0"?>
<package format="3">
  <name>sar_rover</name>
  <version>0.1.0</version>
  <description>Rover subscriber node for the SAR project</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sar_interfaces</depend>
  <depend>nav2_msgs</depend>
  <depend>rclcpp_action</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
